In [6]:
import numpy as np
#1.	Create a two-dimensional NumPy array of shape 5 by 3, representing 5 students and 3 test scores each
scores=np.array([[80,75,90],[70,71,65],[91,63,87],[67,81,63],[78,90,59]])
print(scores.shape)
print(scores.ndim)

(5, 3)
2


In [7]:
#2.	Use slicing to pull out one single student's three scores, then pull out one single test column across all five students.print
print(scores[0])
print(scores[:,0])

[80 75 90]
[80 70 91 67 78]


In [8]:
#3.	Calculate the average score per student, and separately the average score per test, using axis based operations rather than loops.
print(np.mean(scores,axis=1))
print(np.mean(scores,axis=0))

[81.66666667 68.66666667 80.33333333 70.33333333 75.66666667]
[77.2 76.  72.8]


In [9]:
#4.	Multiply the entire array by a scaling factor in a single line of code and observe broadcasting happening.
broadcasted_scores=scores*2
print(broadcasted_scores)

[[160 150 180]
 [140 142 130]
 [182 126 174]
 [134 162 126]
 [156 180 118]]


In [10]:
#5.	Reshape the array into at least two different shapes, printing the shape after each change until the idea feels natural.
new_shape=scores.reshape(3,5)
print(new_shape)
next_new_shape=scores.reshape(15,1)
print(next_new_shape)

[[80 75 90 70 71]
 [65 91 63 87 67]
 [81 63 78 90 59]]
[[80]
 [75]
 [90]
 [70]
 [71]
 [65]
 [91]
 [63]
 [87]
 [67]
 [81]
 [63]
 [78]
 [90]
 [59]]
